package edu.demo;

public interface ConstantsTest {
    int HIGH_PRODUCTIVITY_RAM_TIMING = 12;
    int HIGH_PRODUCTIVITY_RAM_VOLUME = 16000;
    String HIGH_PRODUCTIVITY_RAM_MODEL = "Teams Elite";
    String HIGH_PRODUCTIVITY_CPU_MODEL = "Intel i9";
    int HIGH_PRODUCTIVITY_CPU_CLOCK_SPEED = 6000;
    int HIGH_PRODUCTIVITY_CPU_GENERATION = 12;
    String HIGH_PRODUCTIVITY_STORAGE_MODEL = "Kingston";
    int HIGH_PRODUCTIVITY_STORAGE_VOLUME = 1200;
    String HIGH_PRODUCTIVITY_STORAGE_TYPE = "M.2";

    int MEDIUM_PRODUCTIVITY_RAM_TIMING = 10;
    int MEDIUM_PRODUCTIVITY_RAM_VOLUME = 8000;
    String MEDIUM_PRODUCTIVITY_RAM_MODEL = "Kingston";
    String MEDIUM_PRODUCTIVITY_CPU_MODEL = "AMD Razen";
    int MEDIUM_PRODUCTIVITY_CPU_CLOCK_SPEED = 3000;
    int MEDIUM_PRODUCTIVITY_CPU_GENERATION = 9;
    String MEDIUM_PRODUCTIVITY_STORAGE_MODEL = "Apacer";
    int MEDIUM_PRODUCTIVITY_STORAGE_VOLUME = 500;
    String MEDIUM_PRODUCTIVITY_STORAGE_TYPE = "SSD";

    int LOW_PRODUCTIVITY_RAM_TIMING = 4;
    int LOW_PRODUCTIVITY_RAM_VOLUME = 4000;
    String LOW_PRODUCTIVITY_RAM_MODEL = "Hynix";
    String LOW_PRODUCTIVITY_CPU_MODEL = "ARM X64";
    int LOW_PRODUCTIVITY_CPU_CLOCK_SPEED = 2000;
    int LOW_PRODUCTIVITY_CPU_GENERATION = 7;
    String LOW_PRODUCTIVITY_STORAGE_MODEL = "WD";
    int LOW_PRODUCTIVITY_STORAGE_VOLUME = 400;
    String LOW_PRODUCTIVITY_STORAGE_TYPE = "HDD";


    String HIGH_PRODUCTIVITY = "High Productivity";
    String MEDIUM_PRODUCTIVITY = "Medium Productivity";
    String LOW_PRODUCTIVITY = "Low Productivity";

    double HIGH_PRODUCTIVITY_KOEFICIENT = 1.5;
    double MEDIUM_PRODUCTIVITY_KOEFICIENT = 1.0;
    double LOW_PRODUCTIVITY_KOEFICIENT = 0.5;

}
